export const TACHIYOMI_STABLE_API_URL = "https://api.github.com/repos/inorichi/tachiyomi/releases/latest"
export const TACHIYOMI_PREVIEW_API_URL = "https://api.github.com/repos/tachiyomiorg/android-app-preview/releases/latest"
export const TACHIYOMI_AZ_STABLE_API_URL = "https://api.github.com/repos/inorichi/tachiyomi/releases/latest"
export const TACHIYOMI_AZ_PREVIEW_API_URL = "https://crafty.moe/tachiyomiAZ.apk"
export const TACHIYOMI_J2K_STABLE_API_URL = "https://api.github.com/repos/inorichi/tachiyomi/releases/latest"
export const TACHIYOMI_SY_STABLE_API_URL = "https://api.github.com/repos/inorichi/tachiyomi/releases/latest"
export const TACHIYOMI_SY_PREVIEW_API_URL = "https://api.github.com/repos/jobobby04/TachiyomiSYPreview/releases/latest"
export const NEKO_STABLE_API_URL = "https://api.github.com/repos/CarlosEsco/Neko/releases/latest"
